name: Spell Check
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.17.0
      name: Spellcheck
      with:
        source_files: bylaws.md README.md
        task_name: Markdown
